{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "0d8dd157",
   "metadata": {},
   "outputs": [],
   "source": [
    "import requests\n",
    "import threading\n",
    "import concurrent.futures\n",
    "import pandas as pd\n",
    "import flask\n",
    "from flask import Flask, request\n",
    "import geopy\n",
    "from geopy import Nominatim\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "3fe27fff",
   "metadata": {},
   "outputs": [],
   "source": [
    "key = 'fsq3bR9nCSrR/WbzD82rlvh990Q70wuc8BuuRs0Ypm6fx+w='\n",
    "\n",
    "# this method helps us get long and lat of certain city\n",
    "\n",
    "def get_latlong(b):\n",
    "\n",
    "    \n",
    "    try:\n",
    "    \n",
    "        city = b\n",
    "\n",
    "        geolocator = Nominatim(user_agent = 'Safra')\n",
    "    \n",
    "        loc = geolocator.geocode(city)\n",
    "         \n",
    "        # by default\n",
    "    except: return 'No results found' , f'{b}'\n",
    "    \n",
    "    return loc.latitude , loc.longitude"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "57109941",
   "metadata": {},
   "outputs": [],
   "source": [
    "# this is a test\n",
    "# lat , long = get_latlong('jeddah')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "945cd2fb",
   "metadata": {},
   "outputs": [],
   "source": [
    "# lat , long"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "69949b84",
   "metadata": {},
   "outputs": [],
   "source": [
    "def translate(array):\n",
    "        \n",
    "    # this list contains new translated descriptions\n",
    "    tlds = []\n",
    "    \n",
    "    for desc in array:\n",
    "        try:\n",
    "            # Specifying the language for\n",
    "            # detection\n",
    "            # dbt : detection before translation\n",
    "            dbt = detect(desc)\n",
    "\n",
    "            # saving desc into text to translate\n",
    "            if desc != 'Not Available':\n",
    "                text = desc\n",
    "\n",
    "                blob = TextBlob(text)\n",
    "\n",
    "                # tat : text after translation\n",
    "                tat = blob.translate(from_lang = detect(desc) , to = 'en')\n",
    "                \n",
    "                 # if description is already in english ---> save original description\n",
    "                if dbt != 'en':\n",
    "                    tlds.append(str(tat))\n",
    "                else:\n",
    "                    tlds.append('')\n",
    "\n",
    "            # if not --> save translated description\n",
    "            else:\n",
    "                tlds.append(desc)\n",
    "        except: tlds.append(desc)\n",
    "        \n",
    "    return tlds"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "id": "a2373ab3",
   "metadata": {},
   "outputs": [],
   "source": [
    "def translate2(array):\n",
    "        \n",
    "    # this list contains new translated descriptions\n",
    "    tlds = []\n",
    "    \n",
    "    for desc in array:\n",
    "        \n",
    "        # Specifying the language for\n",
    "        # detection\n",
    "        # dbt : detection before translation\n",
    "        dbt = detect(desc)\n",
    "\n",
    "        # saving desc into text to translate\n",
    "        if desc == 'Not Available':\n",
    "            tlds.append('Not Available')\n",
    "            \n",
    "        elif desc != 'Not Available' and dbt != 'en':\n",
    "\n",
    "            blob = TextBlob(desc)\n",
    "\n",
    "            # tat : text after translation\n",
    "            tat = blob.translate(from_lang = detect(desc) , to = 'en')\n",
    "\n",
    "             # if description is already in english ---> save original description\n",
    "            tlds.append(str(tat))\n",
    "        \n",
    "        elif dbt == 'en':\n",
    "            tlds.append('Not Available')\n",
    "\n",
    "        # if not --> save translated description\n",
    "    return tlds"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "id": "947f558e",
   "metadata": {},
   "outputs": [],
   "source": [
    "def extract_categories(array):\n",
    "    \n",
    "    \"\"\"\n",
    "    array: array of categories\n",
    "    \n",
    "    array[0] = json structure\n",
    "    \n",
    "    so this method extract only name of category out of json\n",
    "    \"\"\"\n",
    "    templist = []\n",
    "    for element in array:\n",
    "        \n",
    "        category = ''\n",
    "        if element != []:\n",
    "            index = 0\n",
    "            for inner_element in element:\n",
    "                index+=1\n",
    "\n",
    "                if index < len(element):\n",
    "                    category += inner_element['name']+','\n",
    "\n",
    "                else:\n",
    "                    category += inner_element['name']\n",
    "            templist.append(category)\n",
    "        else:\n",
    "            category+= 'Not Available'\n",
    "            templist.append(category)\n",
    "    return templist\n",
    "                \n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "id": "23b19792",
   "metadata": {},
   "outputs": [],
   "source": [
    "default = 'https://images.unsplash.com/photo-1517816743773-6e0fd518b4a6?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2803&q=80,https://images.unsplash.com/photo-1614109355930-7640f99a50ba?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1335&q=80,https://images.unsplash.com/photo-1563589425593-c17204c56f56?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1288&q=80'\n",
    "def add_photos(array):\n",
    "    headers = {\n",
    "            \"accept\": \"application/json\",\n",
    "            \"Authorization\": \"fsq3bR9nCSrR/WbzD82rlvh990Q70wuc8BuuRs0Ypm6fx+w=\"\n",
    "                }\n",
    "    # list of links\n",
    "    lol = []\n",
    "    for fsq_id in array:\n",
    "        links = ''\n",
    "        url = f\"https://api.foursquare.com/v3/places/{fsq_id}/photos?limit=5&sort=POPULAR\"\n",
    "        \n",
    "        index = 0\n",
    "        response = ''\n",
    "        try:\n",
    "            response = requests.get(url, headers=headers).json()\n",
    "        \n",
    "        \n",
    "            if response != []:\n",
    "                for element in response:\n",
    "\n",
    "                    if index < len(response):\n",
    "                        links += response[index]['prefix']+'original'+response[index]['suffix']+','\n",
    "                        index+=1\n",
    "                    else:\n",
    "                        links += response[index]['prefix']+'original'+response[index]['suffix']\n",
    "                        index+=1\n",
    "                lol.append(links)\n",
    "            else:\n",
    "                lol.append(default)\n",
    "        except: lol.append(default)\n",
    "    return lol"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "id": "b3bd803f",
   "metadata": {},
   "outputs": [],
   "source": [
    "def retrieve_places(a , c):\n",
    "\n",
    "    \"\"\"\n",
    "    a : condition --- >  example : coffee , art gallery , etc ...\n",
    "    c : city name\n",
    "    \"\"\"\n",
    "    \n",
    "    \n",
    "    lat , long = get_latlong(c)\n",
    "    if type(lat) != str:\n",
    "\n",
    "        if a != '':\n",
    "            fields_url = f\"https://api.foursquare.com/v3/places/search?ll={lat}%2C{long}&query={a}&fields=fsq_id%2Cname%2Ctel%2Cprice%2Crating%2Cdescription%2Clocation%2Ccategories&limit=3\"\n",
    "\n",
    "        else:\n",
    "            fields_url = f\"https://api.foursquare.com/v3/places/search?ll={lat}%2C{long}&fields=fsq_id%2Cname%2Ctel%2Cprice%2Crating%2Cdescription%2Clocation%2Ccategories&limit=3\"\n",
    "\n",
    "\n",
    "        url = fields_url\n",
    "\n",
    "        headers = {\n",
    "            \"Accept\": \"application/json\",\n",
    "            \"Authorization\": key,\n",
    "            \"Accept-Language\": 'en'\n",
    "        }\n",
    "\n",
    "        response = requests.get(url, headers=headers)\n",
    "\n",
    "        data = response.json()\n",
    "\n",
    "        df = pd.json_normalize(data['results'])\n",
    "\n",
    "        #deleting unnecessary columns\n",
    "\n",
    "        try:\n",
    "            df.drop(df.columns.difference(['fsq_id', 'name', 'price', 'rating', 'tel'\n",
    "                                           ,'location.country', 'location.region'\n",
    "                                           , 'description' , 'categories']),axis = 1,inplace=True)\n",
    "\n",
    "        except: df = df\n",
    "            \n",
    "        \n",
    "        \n",
    "        \"\"\"\n",
    "        in this phase we add empty columns if columns are not available already\n",
    "        \n",
    "        ============== remember to change range when changing number of retrieved rows ==============\n",
    "        \"\"\"\n",
    "        if 'price' not in df.columns:\n",
    "            df.insert(len(df.columns) , 'price' , ['Not Available' for i in range(df.shape[0])] )\n",
    "        \n",
    "        if 'description' not in df.columns:\n",
    "            df.insert(len(df.columns) , 'description' , ['Not Available' for i in range(df.shape[0])])\n",
    "        \n",
    "        if 'rating' not in df.columns:\n",
    "            df.insert(len(df.columns) , 'rating' , ['Not Available' for i in range(df.shape[0])])\n",
    "\n",
    "        \n",
    "#         # renaming columns\n",
    "        if 'location.country' in df.columns and 'location.region' in df.columns:\n",
    "            df.rename(columns = {'location.country':'country' , 'location.region':'region'}, inplace = True)\n",
    "    \n",
    "        \n",
    "\n",
    "\n",
    "        # filling nan values\n",
    "\n",
    "        df = df.fillna('Not Available')\n",
    "\n",
    "        \n",
    "\n",
    "        # translating process starts here\n",
    "        # error handling\n",
    "        if 'description' in df.columns:\n",
    "            \n",
    "            df['description'] = [i.replace(',' , '') for i in df['description']]\n",
    "            # extracting\n",
    "#             array = df['description'].to_list()\n",
    "\n",
    "#             # tdl : translated descriptions list\n",
    "\n",
    "#             \"\"\"\n",
    "#             in this line we call function to translate all descriptions as following\n",
    "\n",
    "#             other than english ---> translate\n",
    "\n",
    "#             Not Available ---> keep it as it is\n",
    "\n",
    "#             english description ---> keep it as it's\n",
    "#             \"\"\" \n",
    "            \n",
    "#             tdl = translate2(array)\n",
    "\n",
    "#             # insert it into last \n",
    "#             df.insert(df.columns.get_loc('description')+1  , 'translated_description' , tdl)\n",
    "\n",
    "#         if 'name' in df.columns:\n",
    "#             array_n = df['name'].to_list()\n",
    "            \n",
    "#             tnl = translate(array_n)\n",
    "            \n",
    "#             df.insert(df.columns.get_loc('name')+1 , 'translated_name' , tnl)\n",
    "\n",
    "        \n",
    "#         if 'region' in df.columns:\n",
    "#             array_r = df['region'].to_list()\n",
    "            \n",
    "#             trl = translate(array_r)\n",
    "            \n",
    "#             df.insert(df.columns.get_loc('region')+1 , 'translated_region' , trl)\n",
    "\n",
    "        if 'categories' in df.columns:\n",
    "            templist = df['categories'].to_list()\n",
    "            templist = extract_categories(templist)\n",
    "            \n",
    "            df.drop(['categories'] , inplace = True , axis = 1)\n",
    "            df.insert(len(df.columns), 'categories' , templist)\n",
    "            \n",
    "        try:\n",
    "            # changing datatypes\n",
    "            df = df.astype({'price': str , 'rating': str})\n",
    "        except: df = df\n",
    "        \n",
    "        \n",
    "        '''\n",
    "        adding photos to dataframe \n",
    "        \n",
    "        ==== i suggest to make this function separately rather th\n",
    "        lol : ---> list of links\n",
    "        '''\n",
    "        if 'fsq_id' in df.columns:\n",
    "            lol = add_photos(df['fsq_id'].to_list())\n",
    "\n",
    "            df.insert(len(df.columns) , 'photo_url' , lol)\n",
    "        \n",
    "        data = df.to_json(orient = 'records')\n",
    "        return df, data\n",
    "    else:\n",
    "        return lat , long \n",
    "    "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "id": "e5d5e71b",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "'\\n\\ntest field\\n\\n\\n'"
      ]
     },
     "execution_count": 11,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "'''\n",
    "\n",
    "test field\n",
    "\n",
    "\n",
    "'''"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "id": "5765a8a6",
   "metadata": {},
   "outputs": [],
   "source": [
    "\n",
    "#df , data = retrieve_places('breakfast' , 'london')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 13,
   "id": "947665a0",
   "metadata": {},
   "outputs": [],
   "source": [
    "#df"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 14,
   "id": "3aed5384",
   "metadata": {},
   "outputs": [],
   "source": [
    "# temp"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 15,
   "id": "7307e14e",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      " * Serving Flask app '__main__'\n",
      " * Debug mode: off\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.\n",
      " * Running on http://127.0.0.1:5000\n",
      "Press CTRL+C to quit\n",
      "[2022-10-19 22:35:25,097] ERROR in app: Exception on /api [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Saud\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\flask\\app.py\", line 2525, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Saud\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\flask\\app.py\", line 1822, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Saud\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\flask\\app.py\", line 1820, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Saud\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\flask\\app.py\", line 1796, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
      "  File \"C:\\Users\\Saud\\AppData\\Local\\Temp\\ipykernel_20072\\872093770.py\", line 9, in index\n",
      "    df, data_json = retrieve_places(userInputa , userInputb)\n",
      "  File \"C:\\Users\\Saud\\AppData\\Local\\Temp\\ipykernel_20072\\1278288785.py\", line 9, in retrieve_places\n",
      "    lat , long = get_latlong(c)\n",
      "  File \"C:\\Users\\Saud\\AppData\\Local\\Temp\\ipykernel_20072\\573434723.py\", line 19, in get_latlong\n",
      "    return loc.latitude , loc.longitude\n",
      "AttributeError: 'NoneType' object has no attribute 'latitude'\n",
      "127.0.0.1 - - [19/Oct/2022 22:35:25] \"GET /api?query1=&query2= HTTP/1.1\" 500 -\n",
      "127.0.0.1 - - [19/Oct/2022 22:35:39] \"GET /api?query1=portofino&query2= HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [19/Oct/2022 22:35:57] \"GET /api?query1=portofino&query2= HTTP/1.1\" 200 -\n",
      "[2022-10-19 22:39:03,897] ERROR in app: Exception on /api [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Saud\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\flask\\app.py\", line 2525, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Saud\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\flask\\app.py\", line 1822, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Saud\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\flask\\app.py\", line 1820, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Saud\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\flask\\app.py\", line 1796, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
      "  File \"C:\\Users\\Saud\\AppData\\Local\\Temp\\ipykernel_20072\\872093770.py\", line 9, in index\n",
      "    df, data_json = retrieve_places(userInputa , userInputb)\n",
      "  File \"C:\\Users\\Saud\\AppData\\Local\\Temp\\ipykernel_20072\\1278288785.py\", line 9, in retrieve_places\n",
      "    lat , long = get_latlong(c)\n",
      "  File \"C:\\Users\\Saud\\AppData\\Local\\Temp\\ipykernel_20072\\573434723.py\", line 19, in get_latlong\n",
      "    return loc.latitude , loc.longitude\n",
      "AttributeError: 'NoneType' object has no attribute 'latitude'\n",
      "127.0.0.1 - - [19/Oct/2022 22:39:03] \"GET /api?query1=&query2= HTTP/1.1\" 500 -\n",
      "[2022-10-19 22:39:05,393] ERROR in app: Exception on /api [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Saud\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\flask\\app.py\", line 2525, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Saud\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\flask\\app.py\", line 1822, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Saud\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\flask\\app.py\", line 1820, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Saud\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\flask\\app.py\", line 1796, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
      "  File \"C:\\Users\\Saud\\AppData\\Local\\Temp\\ipykernel_20072\\872093770.py\", line 9, in index\n",
      "    df, data_json = retrieve_places(userInputa , userInputb)\n",
      "  File \"C:\\Users\\Saud\\AppData\\Local\\Temp\\ipykernel_20072\\1278288785.py\", line 9, in retrieve_places\n",
      "    lat , long = get_latlong(c)\n",
      "  File \"C:\\Users\\Saud\\AppData\\Local\\Temp\\ipykernel_20072\\573434723.py\", line 19, in get_latlong\n",
      "    return loc.latitude , loc.longitude\n",
      "AttributeError: 'NoneType' object has no attribute 'latitude'\n",
      "127.0.0.1 - - [19/Oct/2022 22:39:05] \"GET /api?query1=&query2= HTTP/1.1\" 500 -\n",
      "127.0.0.1 - - [19/Oct/2022 22:39:09] \"GET /api?query1=portofino&query2= HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [19/Oct/2022 22:39:16] \"GET /api?query1=portofino&query2= HTTP/1.1\" 200 -\n",
      "[2022-10-19 22:40:22,711] ERROR in app: Exception on /api [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Saud\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\flask\\app.py\", line 2525, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Saud\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\flask\\app.py\", line 1822, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Saud\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\flask\\app.py\", line 1820, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Saud\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\flask\\app.py\", line 1796, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
      "  File \"C:\\Users\\Saud\\AppData\\Local\\Temp\\ipykernel_20072\\872093770.py\", line 9, in index\n",
      "    df, data_json = retrieve_places(userInputa , userInputb)\n",
      "  File \"C:\\Users\\Saud\\AppData\\Local\\Temp\\ipykernel_20072\\1278288785.py\", line 9, in retrieve_places\n",
      "    lat , long = get_latlong(c)\n",
      "  File \"C:\\Users\\Saud\\AppData\\Local\\Temp\\ipykernel_20072\\573434723.py\", line 19, in get_latlong\n",
      "    return loc.latitude , loc.longitude\n",
      "AttributeError: 'NoneType' object has no attribute 'latitude'\n",
      "127.0.0.1 - - [19/Oct/2022 22:40:22] \"GET /api?query1=&query2= HTTP/1.1\" 500 -\n",
      "[2022-10-19 22:40:23,719] ERROR in app: Exception on /api [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Saud\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\flask\\app.py\", line 2525, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Saud\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\flask\\app.py\", line 1822, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Saud\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\flask\\app.py\", line 1820, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Saud\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\flask\\app.py\", line 1796, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
      "  File \"C:\\Users\\Saud\\AppData\\Local\\Temp\\ipykernel_20072\\872093770.py\", line 9, in index\n",
      "    df, data_json = retrieve_places(userInputa , userInputb)\n",
      "  File \"C:\\Users\\Saud\\AppData\\Local\\Temp\\ipykernel_20072\\1278288785.py\", line 9, in retrieve_places\n",
      "    lat , long = get_latlong(c)\n",
      "  File \"C:\\Users\\Saud\\AppData\\Local\\Temp\\ipykernel_20072\\573434723.py\", line 19, in get_latlong\n",
      "    return loc.latitude , loc.longitude\n",
      "AttributeError: 'NoneType' object has no attribute 'latitude'\n",
      "127.0.0.1 - - [19/Oct/2022 22:40:23] \"GET /api?query1=&query2= HTTP/1.1\" 500 -\n",
      "127.0.0.1 - - [19/Oct/2022 22:40:28] \"GET /api?query1=portofino&query2= HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [19/Oct/2022 22:40:29] \"GET /api?query1=portofino&query2= HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [19/Oct/2022 22:40:35] \"GET /api?query1=portofino&query2= HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [19/Oct/2022 22:42:41] \"GET /api?query1=portofino&query2= HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [19/Oct/2022 22:42:48] \"GET /api?query1=portofino&query2= HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [19/Oct/2022 22:42:56] \"GET /api?query1=portofino&query2= HTTP/1.1\" 200 -\n",
      "[2022-10-19 22:43:16,638] ERROR in app: Exception on /api [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Saud\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\flask\\app.py\", line 2525, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Saud\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\flask\\app.py\", line 1822, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Saud\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\flask\\app.py\", line 1820, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Saud\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\flask\\app.py\", line 1796, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
      "  File \"C:\\Users\\Saud\\AppData\\Local\\Temp\\ipykernel_20072\\872093770.py\", line 9, in index\n",
      "    df, data_json = retrieve_places(userInputa , userInputb)\n",
      "  File \"C:\\Users\\Saud\\AppData\\Local\\Temp\\ipykernel_20072\\1278288785.py\", line 9, in retrieve_places\n",
      "    lat , long = get_latlong(c)\n",
      "  File \"C:\\Users\\Saud\\AppData\\Local\\Temp\\ipykernel_20072\\573434723.py\", line 19, in get_latlong\n",
      "    return loc.latitude , loc.longitude\n",
      "AttributeError: 'NoneType' object has no attribute 'latitude'\n",
      "127.0.0.1 - - [19/Oct/2022 22:43:16] \"GET /api?query1=&query2= HTTP/1.1\" 500 -\n",
      "[2022-10-19 22:43:18,134] ERROR in app: Exception on /api [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Saud\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\flask\\app.py\", line 2525, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Saud\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\flask\\app.py\", line 1822, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Saud\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\flask\\app.py\", line 1820, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Saud\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\flask\\app.py\", line 1796, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
      "  File \"C:\\Users\\Saud\\AppData\\Local\\Temp\\ipykernel_20072\\872093770.py\", line 9, in index\n",
      "    df, data_json = retrieve_places(userInputa , userInputb)\n",
      "  File \"C:\\Users\\Saud\\AppData\\Local\\Temp\\ipykernel_20072\\1278288785.py\", line 9, in retrieve_places\n",
      "    lat , long = get_latlong(c)\n",
      "  File \"C:\\Users\\Saud\\AppData\\Local\\Temp\\ipykernel_20072\\573434723.py\", line 19, in get_latlong\n",
      "    return loc.latitude , loc.longitude\n",
      "AttributeError: 'NoneType' object has no attribute 'latitude'\n",
      "127.0.0.1 - - [19/Oct/2022 22:43:18] \"GET /api?query1=&query2= HTTP/1.1\" 500 -\n",
      "127.0.0.1 - - [19/Oct/2022 22:43:23] \"GET /api?query1=portofino&query2= HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [19/Oct/2022 22:43:24] \"GET /api?query1=portofino&query2= HTTP/1.1\" 200 -\n",
      "[2022-10-19 22:43:30,709] ERROR in app: Exception on /api [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Saud\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\flask\\app.py\", line 2525, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Saud\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\flask\\app.py\", line 1822, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Saud\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\flask\\app.py\", line 1820, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Saud\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\flask\\app.py\", line 1796, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
      "  File \"C:\\Users\\Saud\\AppData\\Local\\Temp\\ipykernel_20072\\872093770.py\", line 9, in index\n",
      "    df, data_json = retrieve_places(userInputa , userInputb)\n",
      "  File \"C:\\Users\\Saud\\AppData\\Local\\Temp\\ipykernel_20072\\1278288785.py\", line 9, in retrieve_places\n",
      "    lat , long = get_latlong(c)\n",
      "  File \"C:\\Users\\Saud\\AppData\\Local\\Temp\\ipykernel_20072\\573434723.py\", line 19, in get_latlong\n",
      "    return loc.latitude , loc.longitude\n",
      "AttributeError: 'NoneType' object has no attribute 'latitude'\n",
      "127.0.0.1 - - [19/Oct/2022 22:43:30] \"GET /api?query1=&query2= HTTP/1.1\" 500 -\n",
      "[2022-10-19 22:43:31,207] ERROR in app: Exception on /api [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Saud\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\flask\\app.py\", line 2525, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Saud\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\flask\\app.py\", line 1822, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Saud\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\flask\\app.py\", line 1820, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Saud\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\flask\\app.py\", line 1796, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
      "  File \"C:\\Users\\Saud\\AppData\\Local\\Temp\\ipykernel_20072\\872093770.py\", line 9, in index\n",
      "    df, data_json = retrieve_places(userInputa , userInputb)\n",
      "  File \"C:\\Users\\Saud\\AppData\\Local\\Temp\\ipykernel_20072\\1278288785.py\", line 9, in retrieve_places\n",
      "    lat , long = get_latlong(c)\n",
      "  File \"C:\\Users\\Saud\\AppData\\Local\\Temp\\ipykernel_20072\\573434723.py\", line 19, in get_latlong\n",
      "    return loc.latitude , loc.longitude\n",
      "AttributeError: 'NoneType' object has no attribute 'latitude'\n",
      "127.0.0.1 - - [19/Oct/2022 22:43:31] \"GET /api?query1=&query2= HTTP/1.1\" 500 -\n",
      "127.0.0.1 - - [19/Oct/2022 22:43:37] \"GET /api?query1=portofino&query2= HTTP/1.1\" 200 -\n",
      "[2022-10-19 22:43:54,037] ERROR in app: Exception on /api [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Saud\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\flask\\app.py\", line 2525, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Saud\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\flask\\app.py\", line 1822, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Saud\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\flask\\app.py\", line 1820, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Saud\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\flask\\app.py\", line 1796, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
      "  File \"C:\\Users\\Saud\\AppData\\Local\\Temp\\ipykernel_20072\\872093770.py\", line 9, in index\n",
      "    df, data_json = retrieve_places(userInputa , userInputb)\n",
      "  File \"C:\\Users\\Saud\\AppData\\Local\\Temp\\ipykernel_20072\\1278288785.py\", line 9, in retrieve_places\n",
      "    lat , long = get_latlong(c)\n",
      "  File \"C:\\Users\\Saud\\AppData\\Local\\Temp\\ipykernel_20072\\573434723.py\", line 19, in get_latlong\n",
      "    return loc.latitude , loc.longitude\n",
      "AttributeError: 'NoneType' object has no attribute 'latitude'\n",
      "127.0.0.1 - - [19/Oct/2022 22:43:54] \"GET /api?query1=&query2= HTTP/1.1\" 500 -\n",
      "[2022-10-19 22:43:54,549] ERROR in app: Exception on /api [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Saud\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\flask\\app.py\", line 2525, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Saud\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\flask\\app.py\", line 1822, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Saud\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\flask\\app.py\", line 1820, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Saud\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\flask\\app.py\", line 1796, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
      "  File \"C:\\Users\\Saud\\AppData\\Local\\Temp\\ipykernel_20072\\872093770.py\", line 9, in index\n",
      "    df, data_json = retrieve_places(userInputa , userInputb)\n",
      "  File \"C:\\Users\\Saud\\AppData\\Local\\Temp\\ipykernel_20072\\1278288785.py\", line 9, in retrieve_places\n",
      "    lat , long = get_latlong(c)\n",
      "  File \"C:\\Users\\Saud\\AppData\\Local\\Temp\\ipykernel_20072\\573434723.py\", line 19, in get_latlong\n",
      "    return loc.latitude , loc.longitude\n",
      "AttributeError: 'NoneType' object has no attribute 'latitude'\n",
      "127.0.0.1 - - [19/Oct/2022 22:43:54] \"GET /api?query1=&query2= HTTP/1.1\" 500 -\n",
      "[2022-10-19 22:44:00,486] ERROR in app: Exception on /api [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Saud\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\flask\\app.py\", line 2525, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Saud\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\flask\\app.py\", line 1822, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Saud\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\flask\\app.py\", line 1820, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Saud\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\flask\\app.py\", line 1796, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
      "  File \"C:\\Users\\Saud\\AppData\\Local\\Temp\\ipykernel_20072\\872093770.py\", line 9, in index\n",
      "    df, data_json = retrieve_places(userInputa , userInputb)\n",
      "  File \"C:\\Users\\Saud\\AppData\\Local\\Temp\\ipykernel_20072\\1278288785.py\", line 9, in retrieve_places\n",
      "    lat , long = get_latlong(c)\n",
      "  File \"C:\\Users\\Saud\\AppData\\Local\\Temp\\ipykernel_20072\\573434723.py\", line 19, in get_latlong\n",
      "    return loc.latitude , loc.longitude\n",
      "AttributeError: 'NoneType' object has no attribute 'latitude'\n",
      "127.0.0.1 - - [19/Oct/2022 22:44:00] \"GET /api?query1=&query2= HTTP/1.1\" 500 -\n",
      "127.0.0.1 - - [19/Oct/2022 22:44:00] \"GET /api?query1=portofino&query2= HTTP/1.1\" 200 -\n",
      "[2022-10-19 22:44:00,988] ERROR in app: Exception on /api [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Saud\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\flask\\app.py\", line 2525, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Saud\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\flask\\app.py\", line 1822, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Saud\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\flask\\app.py\", line 1820, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Saud\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\flask\\app.py\", line 1796, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
      "  File \"C:\\Users\\Saud\\AppData\\Local\\Temp\\ipykernel_20072\\872093770.py\", line 9, in index\n",
      "    df, data_json = retrieve_places(userInputa , userInputb)\n",
      "  File \"C:\\Users\\Saud\\AppData\\Local\\Temp\\ipykernel_20072\\1278288785.py\", line 9, in retrieve_places\n",
      "    lat , long = get_latlong(c)\n",
      "  File \"C:\\Users\\Saud\\AppData\\Local\\Temp\\ipykernel_20072\\573434723.py\", line 19, in get_latlong\n",
      "    return loc.latitude , loc.longitude\n",
      "AttributeError: 'NoneType' object has no attribute 'latitude'\n",
      "127.0.0.1 - - [19/Oct/2022 22:44:00] \"GET /api?query1=&query2= HTTP/1.1\" 500 -\n",
      "127.0.0.1 - - [19/Oct/2022 22:44:06] \"GET /api?query1=portofino&query2= HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [19/Oct/2022 22:44:08] \"GET /api?query1=portofino&query2= HTTP/1.1\" 200 -\n",
      "[2022-10-19 22:45:06,454] ERROR in app: Exception on /api [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Saud\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\flask\\app.py\", line 2525, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Saud\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\flask\\app.py\", line 1822, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Saud\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\flask\\app.py\", line 1820, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Saud\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\flask\\app.py\", line 1796, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
      "  File \"C:\\Users\\Saud\\AppData\\Local\\Temp\\ipykernel_20072\\872093770.py\", line 9, in index\n",
      "    df, data_json = retrieve_places(userInputa , userInputb)\n",
      "  File \"C:\\Users\\Saud\\AppData\\Local\\Temp\\ipykernel_20072\\1278288785.py\", line 9, in retrieve_places\n",
      "    lat , long = get_latlong(c)\n",
      "  File \"C:\\Users\\Saud\\AppData\\Local\\Temp\\ipykernel_20072\\573434723.py\", line 19, in get_latlong\n",
      "    return loc.latitude , loc.longitude\n",
      "AttributeError: 'NoneType' object has no attribute 'latitude'\n",
      "127.0.0.1 - - [19/Oct/2022 22:45:06] \"GET /api?query1=&query2= HTTP/1.1\" 500 -\n",
      "[2022-10-19 22:45:06,948] ERROR in app: Exception on /api [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Saud\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\flask\\app.py\", line 2525, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Saud\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\flask\\app.py\", line 1822, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Saud\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\flask\\app.py\", line 1820, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Saud\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\flask\\app.py\", line 1796, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
      "  File \"C:\\Users\\Saud\\AppData\\Local\\Temp\\ipykernel_20072\\872093770.py\", line 9, in index\n",
      "    df, data_json = retrieve_places(userInputa , userInputb)\n",
      "  File \"C:\\Users\\Saud\\AppData\\Local\\Temp\\ipykernel_20072\\1278288785.py\", line 9, in retrieve_places\n",
      "    lat , long = get_latlong(c)\n",
      "  File \"C:\\Users\\Saud\\AppData\\Local\\Temp\\ipykernel_20072\\573434723.py\", line 19, in get_latlong\n",
      "    return loc.latitude , loc.longitude\n",
      "AttributeError: 'NoneType' object has no attribute 'latitude'\n",
      "127.0.0.1 - - [19/Oct/2022 22:45:06] \"GET /api?query1=&query2= HTTP/1.1\" 500 -\n",
      "127.0.0.1 - - [19/Oct/2022 22:45:13] \"GET /api?query1=portofino&query2= HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [19/Oct/2022 22:45:13] \"GET /api?query1=portofino&query2= HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [19/Oct/2022 22:45:35] \"GET /api?query1=portofino&query2= HTTP/1.1\" 200 -\n",
      "[2022-10-19 22:45:43,662] ERROR in app: Exception on /api [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Saud\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\flask\\app.py\", line 2525, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Saud\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\flask\\app.py\", line 1822, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Saud\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\flask\\app.py\", line 1820, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Saud\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\flask\\app.py\", line 1796, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
      "  File \"C:\\Users\\Saud\\AppData\\Local\\Temp\\ipykernel_20072\\872093770.py\", line 9, in index\n",
      "    df, data_json = retrieve_places(userInputa , userInputb)\n",
      "  File \"C:\\Users\\Saud\\AppData\\Local\\Temp\\ipykernel_20072\\1278288785.py\", line 9, in retrieve_places\n",
      "    lat , long = get_latlong(c)\n",
      "  File \"C:\\Users\\Saud\\AppData\\Local\\Temp\\ipykernel_20072\\573434723.py\", line 19, in get_latlong\n",
      "    return loc.latitude , loc.longitude\n",
      "AttributeError: 'NoneType' object has no attribute 'latitude'\n",
      "127.0.0.1 - - [19/Oct/2022 22:45:43] \"GET /api?query1=&query2= HTTP/1.1\" 500 -\n",
      "[2022-10-19 22:45:44,160] ERROR in app: Exception on /api [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Saud\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\flask\\app.py\", line 2525, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Saud\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\flask\\app.py\", line 1822, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Saud\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\flask\\app.py\", line 1820, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Saud\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\flask\\app.py\", line 1796, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
      "  File \"C:\\Users\\Saud\\AppData\\Local\\Temp\\ipykernel_20072\\872093770.py\", line 9, in index\n",
      "    df, data_json = retrieve_places(userInputa , userInputb)\n",
      "  File \"C:\\Users\\Saud\\AppData\\Local\\Temp\\ipykernel_20072\\1278288785.py\", line 9, in retrieve_places\n",
      "    lat , long = get_latlong(c)\n",
      "  File \"C:\\Users\\Saud\\AppData\\Local\\Temp\\ipykernel_20072\\573434723.py\", line 19, in get_latlong\n",
      "    return loc.latitude , loc.longitude\n",
      "AttributeError: 'NoneType' object has no attribute 'latitude'\n",
      "127.0.0.1 - - [19/Oct/2022 22:45:44] \"GET /api?query1=&query2= HTTP/1.1\" 500 -\n",
      "127.0.0.1 - - [19/Oct/2022 22:45:51] \"GET /api?query1=portofino&query2= HTTP/1.1\" 200 -\n",
      "[2022-10-19 22:46:09,458] ERROR in app: Exception on /api [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Saud\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\flask\\app.py\", line 2525, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Saud\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\flask\\app.py\", line 1822, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Saud\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\flask\\app.py\", line 1820, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Saud\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\flask\\app.py\", line 1796, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
      "  File \"C:\\Users\\Saud\\AppData\\Local\\Temp\\ipykernel_20072\\872093770.py\", line 9, in index\n",
      "    df, data_json = retrieve_places(userInputa , userInputb)\n",
      "  File \"C:\\Users\\Saud\\AppData\\Local\\Temp\\ipykernel_20072\\1278288785.py\", line 9, in retrieve_places\n",
      "    lat , long = get_latlong(c)\n",
      "  File \"C:\\Users\\Saud\\AppData\\Local\\Temp\\ipykernel_20072\\573434723.py\", line 19, in get_latlong\n",
      "    return loc.latitude , loc.longitude\n",
      "AttributeError: 'NoneType' object has no attribute 'latitude'\n",
      "127.0.0.1 - - [19/Oct/2022 22:46:09] \"GET /api?query1=&query2= HTTP/1.1\" 500 -\n",
      "[2022-10-19 22:46:09,945] ERROR in app: Exception on /api [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Saud\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\flask\\app.py\", line 2525, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Saud\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\flask\\app.py\", line 1822, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Saud\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\flask\\app.py\", line 1820, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Saud\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\flask\\app.py\", line 1796, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
      "  File \"C:\\Users\\Saud\\AppData\\Local\\Temp\\ipykernel_20072\\872093770.py\", line 9, in index\n",
      "    df, data_json = retrieve_places(userInputa , userInputb)\n",
      "  File \"C:\\Users\\Saud\\AppData\\Local\\Temp\\ipykernel_20072\\1278288785.py\", line 9, in retrieve_places\n",
      "    lat , long = get_latlong(c)\n",
      "  File \"C:\\Users\\Saud\\AppData\\Local\\Temp\\ipykernel_20072\\573434723.py\", line 19, in get_latlong\n",
      "    return loc.latitude , loc.longitude\n",
      "AttributeError: 'NoneType' object has no attribute 'latitude'\n",
      "127.0.0.1 - - [19/Oct/2022 22:46:09] \"GET /api?query1=&query2= HTTP/1.1\" 500 -\n",
      "127.0.0.1 - - [19/Oct/2022 22:46:16] \"GET /api?query1=portofino&query2= HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [19/Oct/2022 22:46:16] \"GET /api?query1=portofino&query2= HTTP/1.1\" 200 -\n",
      "[2022-10-19 22:46:27,987] ERROR in app: Exception on /api [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Saud\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\flask\\app.py\", line 2525, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Saud\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\flask\\app.py\", line 1822, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Saud\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\flask\\app.py\", line 1820, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Saud\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\flask\\app.py\", line 1796, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
      "  File \"C:\\Users\\Saud\\AppData\\Local\\Temp\\ipykernel_20072\\872093770.py\", line 9, in index\n",
      "    df, data_json = retrieve_places(userInputa , userInputb)\n",
      "  File \"C:\\Users\\Saud\\AppData\\Local\\Temp\\ipykernel_20072\\1278288785.py\", line 9, in retrieve_places\n",
      "    lat , long = get_latlong(c)\n",
      "  File \"C:\\Users\\Saud\\AppData\\Local\\Temp\\ipykernel_20072\\573434723.py\", line 19, in get_latlong\n",
      "    return loc.latitude , loc.longitude\n",
      "AttributeError: 'NoneType' object has no attribute 'latitude'\n",
      "127.0.0.1 - - [19/Oct/2022 22:46:27] \"GET /api?query1=&query2= HTTP/1.1\" 500 -\n",
      "[2022-10-19 22:46:28,985] ERROR in app: Exception on /api [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Saud\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\flask\\app.py\", line 2525, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Saud\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\flask\\app.py\", line 1822, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Saud\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\flask\\app.py\", line 1820, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Saud\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\flask\\app.py\", line 1796, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
      "  File \"C:\\Users\\Saud\\AppData\\Local\\Temp\\ipykernel_20072\\872093770.py\", line 9, in index\n",
      "    df, data_json = retrieve_places(userInputa , userInputb)\n",
      "  File \"C:\\Users\\Saud\\AppData\\Local\\Temp\\ipykernel_20072\\1278288785.py\", line 9, in retrieve_places\n",
      "    lat , long = get_latlong(c)\n",
      "  File \"C:\\Users\\Saud\\AppData\\Local\\Temp\\ipykernel_20072\\573434723.py\", line 19, in get_latlong\n",
      "    return loc.latitude , loc.longitude\n",
      "AttributeError: 'NoneType' object has no attribute 'latitude'\n",
      "127.0.0.1 - - [19/Oct/2022 22:46:28] \"GET /api?query1=&query2= HTTP/1.1\" 500 -\n",
      "127.0.0.1 - - [19/Oct/2022 22:46:32] \"GET /api?query1=portofino&query2= HTTP/1.1\" 200 -\n",
      "[2022-10-19 22:46:37,924] ERROR in app: Exception on /api [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Saud\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\flask\\app.py\", line 2525, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Saud\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\flask\\app.py\", line 1822, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Saud\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\flask\\app.py\", line 1820, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Saud\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\flask\\app.py\", line 1796, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
      "  File \"C:\\Users\\Saud\\AppData\\Local\\Temp\\ipykernel_20072\\872093770.py\", line 9, in index\n",
      "    df, data_json = retrieve_places(userInputa , userInputb)\n",
      "  File \"C:\\Users\\Saud\\AppData\\Local\\Temp\\ipykernel_20072\\1278288785.py\", line 9, in retrieve_places\n",
      "    lat , long = get_latlong(c)\n",
      "  File \"C:\\Users\\Saud\\AppData\\Local\\Temp\\ipykernel_20072\\573434723.py\", line 19, in get_latlong\n",
      "    return loc.latitude , loc.longitude\n",
      "AttributeError: 'NoneType' object has no attribute 'latitude'\n",
      "127.0.0.1 - - [19/Oct/2022 22:46:37] \"GET /api?query1=&query2= HTTP/1.1\" 500 -\n",
      "[2022-10-19 22:46:38,431] ERROR in app: Exception on /api [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Saud\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\flask\\app.py\", line 2525, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Saud\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\flask\\app.py\", line 1822, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Saud\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\flask\\app.py\", line 1820, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Saud\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\flask\\app.py\", line 1796, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
      "  File \"C:\\Users\\Saud\\AppData\\Local\\Temp\\ipykernel_20072\\872093770.py\", line 9, in index\n",
      "    df, data_json = retrieve_places(userInputa , userInputb)\n",
      "  File \"C:\\Users\\Saud\\AppData\\Local\\Temp\\ipykernel_20072\\1278288785.py\", line 9, in retrieve_places\n",
      "    lat , long = get_latlong(c)\n",
      "  File \"C:\\Users\\Saud\\AppData\\Local\\Temp\\ipykernel_20072\\573434723.py\", line 19, in get_latlong\n",
      "    return loc.latitude , loc.longitude\n",
      "AttributeError: 'NoneType' object has no attribute 'latitude'\n",
      "127.0.0.1 - - [19/Oct/2022 22:46:38] \"GET /api?query1=&query2= HTTP/1.1\" 500 -\n",
      "127.0.0.1 - - [19/Oct/2022 22:46:42] \"GET /api?query1=portofino&query2= HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [19/Oct/2022 22:46:44] \"GET /api?query1=portofino&query2= HTTP/1.1\" 200 -\n",
      "[2022-10-19 22:46:46,937] ERROR in app: Exception on /api [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Saud\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\flask\\app.py\", line 2525, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Saud\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\flask\\app.py\", line 1822, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Saud\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\flask\\app.py\", line 1820, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Saud\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\flask\\app.py\", line 1796, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
      "  File \"C:\\Users\\Saud\\AppData\\Local\\Temp\\ipykernel_20072\\872093770.py\", line 9, in index\n",
      "    df, data_json = retrieve_places(userInputa , userInputb)\n",
      "  File \"C:\\Users\\Saud\\AppData\\Local\\Temp\\ipykernel_20072\\1278288785.py\", line 9, in retrieve_places\n",
      "    lat , long = get_latlong(c)\n",
      "  File \"C:\\Users\\Saud\\AppData\\Local\\Temp\\ipykernel_20072\\573434723.py\", line 19, in get_latlong\n",
      "    return loc.latitude , loc.longitude\n",
      "AttributeError: 'NoneType' object has no attribute 'latitude'\n",
      "127.0.0.1 - - [19/Oct/2022 22:46:46] \"GET /api?query1=&query2= HTTP/1.1\" 500 -\n",
      "[2022-10-19 22:46:47,435] ERROR in app: Exception on /api [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Saud\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\flask\\app.py\", line 2525, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Saud\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\flask\\app.py\", line 1822, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Saud\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\flask\\app.py\", line 1820, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Saud\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\flask\\app.py\", line 1796, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
      "  File \"C:\\Users\\Saud\\AppData\\Local\\Temp\\ipykernel_20072\\872093770.py\", line 9, in index\n",
      "    df, data_json = retrieve_places(userInputa , userInputb)\n",
      "  File \"C:\\Users\\Saud\\AppData\\Local\\Temp\\ipykernel_20072\\1278288785.py\", line 9, in retrieve_places\n",
      "    lat , long = get_latlong(c)\n",
      "  File \"C:\\Users\\Saud\\AppData\\Local\\Temp\\ipykernel_20072\\573434723.py\", line 19, in get_latlong\n",
      "    return loc.latitude , loc.longitude\n",
      "AttributeError: 'NoneType' object has no attribute 'latitude'\n",
      "127.0.0.1 - - [19/Oct/2022 22:46:47] \"GET /api?query1=&query2= HTTP/1.1\" 500 -\n",
      "127.0.0.1 - - [19/Oct/2022 22:46:51] \"GET /api?query1=portofino&query2= HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [19/Oct/2022 22:46:54] \"GET /api?query1=portofino&query2= HTTP/1.1\" 200 -\n",
      "[2022-10-19 22:47:02,644] ERROR in app: Exception on /api [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Saud\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\flask\\app.py\", line 2525, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Saud\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\flask\\app.py\", line 1822, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Saud\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\flask\\app.py\", line 1820, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Saud\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\flask\\app.py\", line 1796, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
      "  File \"C:\\Users\\Saud\\AppData\\Local\\Temp\\ipykernel_20072\\872093770.py\", line 9, in index\n",
      "    df, data_json = retrieve_places(userInputa , userInputb)\n",
      "  File \"C:\\Users\\Saud\\AppData\\Local\\Temp\\ipykernel_20072\\1278288785.py\", line 9, in retrieve_places\n",
      "    lat , long = get_latlong(c)\n",
      "  File \"C:\\Users\\Saud\\AppData\\Local\\Temp\\ipykernel_20072\\573434723.py\", line 19, in get_latlong\n",
      "    return loc.latitude , loc.longitude\n",
      "AttributeError: 'NoneType' object has no attribute 'latitude'\n",
      "127.0.0.1 - - [19/Oct/2022 22:47:02] \"GET /api?query1=&query2= HTTP/1.1\" 500 -\n",
      "[2022-10-19 22:47:03,142] ERROR in app: Exception on /api [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Saud\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\flask\\app.py\", line 2525, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Saud\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\flask\\app.py\", line 1822, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Saud\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\flask\\app.py\", line 1820, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Saud\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\flask\\app.py\", line 1796, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
      "  File \"C:\\Users\\Saud\\AppData\\Local\\Temp\\ipykernel_20072\\872093770.py\", line 9, in index\n",
      "    df, data_json = retrieve_places(userInputa , userInputb)\n",
      "  File \"C:\\Users\\Saud\\AppData\\Local\\Temp\\ipykernel_20072\\1278288785.py\", line 9, in retrieve_places\n",
      "    lat , long = get_latlong(c)\n",
      "  File \"C:\\Users\\Saud\\AppData\\Local\\Temp\\ipykernel_20072\\573434723.py\", line 19, in get_latlong\n",
      "    return loc.latitude , loc.longitude\n",
      "AttributeError: 'NoneType' object has no attribute 'latitude'\n",
      "127.0.0.1 - - [19/Oct/2022 22:47:03] \"GET /api?query1=&query2= HTTP/1.1\" 500 -\n",
      "127.0.0.1 - - [19/Oct/2022 22:47:08] \"GET /api?query1=portofino&query2= HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [19/Oct/2022 22:47:08] \"GET /api?query1=portofino&query2= HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [19/Oct/2022 22:47:25] \"GET /api?query1=portofino&query2= HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [19/Oct/2022 22:47:35] \"GET /api?query1=amalfi%20coast&query2= HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [19/Oct/2022 22:47:52] \"GET /api?query1=amalfi%20coast&query2= HTTP/1.1\" 200 -\n",
      "[2022-10-19 22:48:53,884] ERROR in app: Exception on /api [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Saud\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\flask\\app.py\", line 2525, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Saud\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\flask\\app.py\", line 1822, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Saud\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\flask\\app.py\", line 1820, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Saud\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\flask\\app.py\", line 1796, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
      "  File \"C:\\Users\\Saud\\AppData\\Local\\Temp\\ipykernel_20072\\872093770.py\", line 9, in index\n",
      "    df, data_json = retrieve_places(userInputa , userInputb)\n",
      "  File \"C:\\Users\\Saud\\AppData\\Local\\Temp\\ipykernel_20072\\1278288785.py\", line 9, in retrieve_places\n",
      "    lat , long = get_latlong(c)\n",
      "  File \"C:\\Users\\Saud\\AppData\\Local\\Temp\\ipykernel_20072\\573434723.py\", line 19, in get_latlong\n",
      "    return loc.latitude , loc.longitude\n",
      "AttributeError: 'NoneType' object has no attribute 'latitude'\n",
      "127.0.0.1 - - [19/Oct/2022 22:48:53] \"GET /api?query1=&query2= HTTP/1.1\" 500 -\n",
      "[2022-10-19 22:48:54,380] ERROR in app: Exception on /api [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Saud\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\flask\\app.py\", line 2525, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Saud\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\flask\\app.py\", line 1822, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Saud\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\flask\\app.py\", line 1820, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Saud\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\flask\\app.py\", line 1796, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
      "  File \"C:\\Users\\Saud\\AppData\\Local\\Temp\\ipykernel_20072\\872093770.py\", line 9, in index\n",
      "    df, data_json = retrieve_places(userInputa , userInputb)\n",
      "  File \"C:\\Users\\Saud\\AppData\\Local\\Temp\\ipykernel_20072\\1278288785.py\", line 9, in retrieve_places\n",
      "    lat , long = get_latlong(c)\n",
      "  File \"C:\\Users\\Saud\\AppData\\Local\\Temp\\ipykernel_20072\\573434723.py\", line 19, in get_latlong\n",
      "    return loc.latitude , loc.longitude\n",
      "AttributeError: 'NoneType' object has no attribute 'latitude'\n",
      "127.0.0.1 - - [19/Oct/2022 22:48:54] \"GET /api?query1=&query2= HTTP/1.1\" 500 -\n",
      "127.0.0.1 - - [19/Oct/2022 22:48:57] \"GET /api?query1=amalfi%20coast&query2= HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [19/Oct/2022 22:48:59] \"GET /api?query1=amalfi%20coast&query2= HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [19/Oct/2022 22:49:02] \"GET /api?query1=amalfi%20coast&query2= HTTP/1.1\" 200 -\n",
      "[2022-10-19 22:49:24,933] ERROR in app: Exception on /api [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Saud\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\flask\\app.py\", line 2525, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Saud\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\flask\\app.py\", line 1822, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Saud\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\flask\\app.py\", line 1820, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Saud\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\flask\\app.py\", line 1796, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
      "  File \"C:\\Users\\Saud\\AppData\\Local\\Temp\\ipykernel_20072\\872093770.py\", line 9, in index\n",
      "    df, data_json = retrieve_places(userInputa , userInputb)\n",
      "  File \"C:\\Users\\Saud\\AppData\\Local\\Temp\\ipykernel_20072\\1278288785.py\", line 9, in retrieve_places\n",
      "    lat , long = get_latlong(c)\n",
      "  File \"C:\\Users\\Saud\\AppData\\Local\\Temp\\ipykernel_20072\\573434723.py\", line 19, in get_latlong\n",
      "    return loc.latitude , loc.longitude\n",
      "AttributeError: 'NoneType' object has no attribute 'latitude'\n",
      "127.0.0.1 - - [19/Oct/2022 22:49:24] \"GET /api?query1=&query2= HTTP/1.1\" 500 -\n",
      "[2022-10-19 22:49:25,936] ERROR in app: Exception on /api [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Saud\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\flask\\app.py\", line 2525, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Saud\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\flask\\app.py\", line 1822, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Saud\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\flask\\app.py\", line 1820, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Saud\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\flask\\app.py\", line 1796, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
      "  File \"C:\\Users\\Saud\\AppData\\Local\\Temp\\ipykernel_20072\\872093770.py\", line 9, in index\n",
      "    df, data_json = retrieve_places(userInputa , userInputb)\n",
      "  File \"C:\\Users\\Saud\\AppData\\Local\\Temp\\ipykernel_20072\\1278288785.py\", line 9, in retrieve_places\n",
      "    lat , long = get_latlong(c)\n",
      "  File \"C:\\Users\\Saud\\AppData\\Local\\Temp\\ipykernel_20072\\573434723.py\", line 19, in get_latlong\n",
      "    return loc.latitude , loc.longitude\n",
      "AttributeError: 'NoneType' object has no attribute 'latitude'\n",
      "127.0.0.1 - - [19/Oct/2022 22:49:25] \"GET /api?query1=&query2= HTTP/1.1\" 500 -\n",
      "127.0.0.1 - - [19/Oct/2022 22:49:28] \"GET /api?query1=amalfi%20coast&query2= HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [19/Oct/2022 22:49:30] \"GET /api?query1=amalfi%20coast&query2= HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [19/Oct/2022 22:49:33] \"GET /api?query1=amalfi%20coast&query2= HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [19/Oct/2022 22:49:41] \"GET /api?query1=amalfi%20coast&query2= HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [19/Oct/2022 22:49:54] \"GET /api?query1=amalfi%20coast&query2= HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [19/Oct/2022 22:50:30] \"GET /api?query1=riyadh&query2=myazu HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [19/Oct/2022 22:50:47] \"GET /api?query1=riyadh&query2=myazu HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [19/Oct/2022 22:50:54] \"GET /api?query1=riyadh&query2=myazu HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [19/Oct/2022 22:51:12] \"GET /api?query1=riyadh&query2=myazu HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [19/Oct/2022 22:51:25] \"GET /api?query1=riyadh&query2=shawerma HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [19/Oct/2022 22:54:17] \"GET /api?query1=riyadh&query2=shawerma HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [19/Oct/2022 22:54:23] \"GET /api?query1=riyadh&query2=tailor HTTP/1.1\" 200 -\n",
      "[2022-10-19 22:54:47,419] ERROR in app: Exception on /api [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Saud\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\flask\\app.py\", line 2525, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Saud\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\flask\\app.py\", line 1822, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Saud\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\flask\\app.py\", line 1820, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Saud\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\flask\\app.py\", line 1796, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
      "  File \"C:\\Users\\Saud\\AppData\\Local\\Temp\\ipykernel_20072\\872093770.py\", line 9, in index\n",
      "    df, data_json = retrieve_places(userInputa , userInputb)\n",
      "  File \"C:\\Users\\Saud\\AppData\\Local\\Temp\\ipykernel_20072\\1278288785.py\", line 9, in retrieve_places\n",
      "    lat , long = get_latlong(c)\n",
      "  File \"C:\\Users\\Saud\\AppData\\Local\\Temp\\ipykernel_20072\\573434723.py\", line 19, in get_latlong\n",
      "    return loc.latitude , loc.longitude\n",
      "AttributeError: 'NoneType' object has no attribute 'latitude'\n",
      "127.0.0.1 - - [19/Oct/2022 22:54:47] \"GET /api?query1=&query2= HTTP/1.1\" 500 -\n",
      "127.0.0.1 - - [19/Oct/2022 22:55:05] \"GET /api?query1=riyadh&query2=tailor HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [19/Oct/2022 22:55:39] \"GET /api?query1=riyadh&query2=jarir HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [19/Oct/2022 22:56:01] \"GET /api?query1=riyadh&query2=shawerma HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [19/Oct/2022 22:56:59] \"GET /api?query1=riyadh&query2=burger HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [19/Oct/2022 22:57:14] \"GET /api?query1=riyadh&query2=burger HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [19/Oct/2022 22:57:24] \"GET /api?query1=riyadh&query2=bunch HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [19/Oct/2022 22:57:53] \"GET /api?query1=riyadh&query2=airport HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [19/Oct/2022 22:58:03] \"GET /api?query1=riyadh&query2=airport HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [19/Oct/2022 22:59:01] \"GET /api?query1=riyadh&query2=airport HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [19/Oct/2022 22:59:26] \"GET /api?query1=riyadh&query2=cinema HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [19/Oct/2022 22:59:41] \"GET /api?query1=riyadh&query2=cinema HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [19/Oct/2022 22:59:51] \"GET /api?query1=riyadh&query2=cinema HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [19/Oct/2022 23:00:08] \"GET /api?query1=riyadh&query2=cinema HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [19/Oct/2022 23:00:16] \"GET /api?query1=riyadh&query2=cinema HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [19/Oct/2022 23:00:24] \"GET /api?query1=riyadh&query2=jolt HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [19/Oct/2022 23:00:37] \"GET /api?query1=riyadh&query2=jolt HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [19/Oct/2022 23:01:19] \"GET /api?query1=riyadh&query2=mama%20noura HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [19/Oct/2022 23:01:33] \"GET /api?query1=riyadh&query2=mama%20noura HTTP/1.1\" 200 -\n",
      "[2022-10-19 23:01:58,065] ERROR in app: Exception on /api [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Saud\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\flask\\app.py\", line 2525, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Saud\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\flask\\app.py\", line 1822, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Saud\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\flask\\app.py\", line 1820, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Saud\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\flask\\app.py\", line 1796, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
      "  File \"C:\\Users\\Saud\\AppData\\Local\\Temp\\ipykernel_20072\\872093770.py\", line 9, in index\n",
      "    df, data_json = retrieve_places(userInputa , userInputb)\n",
      "  File \"C:\\Users\\Saud\\AppData\\Local\\Temp\\ipykernel_20072\\1278288785.py\", line 9, in retrieve_places\n",
      "    lat , long = get_latlong(c)\n",
      "  File \"C:\\Users\\Saud\\AppData\\Local\\Temp\\ipykernel_20072\\573434723.py\", line 19, in get_latlong\n",
      "    return loc.latitude , loc.longitude\n",
      "AttributeError: 'NoneType' object has no attribute 'latitude'\n",
      "127.0.0.1 - - [19/Oct/2022 23:01:58] \"GET /api?query1=&query2= HTTP/1.1\" 500 -\n",
      "127.0.0.1 - - [19/Oct/2022 23:02:23] \"GET /api?query1=jeddah&query2=cafe HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [19/Oct/2022 23:02:41] \"GET /api?query1=jeddah&query2=cafe HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [19/Oct/2022 23:02:45] \"GET /api?query1=jeddah&query2=cafe HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [19/Oct/2022 23:02:50] \"GET /api?query1=jeddah&query2=cafe HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [19/Oct/2022 23:03:01] \"GET /api?query1=riyadh&query2=gym HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [19/Oct/2022 23:03:17] \"GET /api?query1=riyadh&query2=gymnastic HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [19/Oct/2022 23:03:30] \"GET /api?query1=riyadh&query2=sport HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [19/Oct/2022 23:03:44] \"GET /api?query1=riyadh&query2=football HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [19/Oct/2022 23:04:15] \"GET /api?query1=riyadh&query2=vegetables HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [19/Oct/2022 23:04:47] \"GET /api?query1=riyadh&query2=vegetables HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [19/Oct/2022 23:04:53] \"GET /api?query1=riyadh&query2=vegetables HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [19/Oct/2022 23:04:59] \"GET /api?query1=riyadh&query2=vegetables HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [19/Oct/2022 23:05:08] \"GET /api?query1=riyadh&query2=urth HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [19/Oct/2022 23:05:24] \"GET /api?query1=riyadh&query2=urth HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [19/Oct/2022 23:05:26] \"GET /api?query1=riyadh&query2=urth HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [19/Oct/2022 23:05:49] \"GET /api?query1=riyadh&query2=urth HTTP/1.1\" 200 -\n"
     ]
    }
   ],
   "source": [
    "app = Flask(__name__)\n",
    "\n",
    "\n",
    "@app.route('/api' , methods = ['GET' , 'POST'])\n",
    "\n",
    "def index():\n",
    "    userInputa = str(request.args['query2'])\n",
    "    userInputb = str(request.args['query1'])\n",
    "    df, data_json = retrieve_places(userInputa , userInputb)\n",
    "\n",
    "    return data_json\n",
    "\n",
    "\n",
    "if __name__ == \"__main__\":\n",
    "    app.run()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "759a8a06",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.12"
  },
  "vscode": {
   "interpreter": {
    "hash": "2fe5aaee289c0fafb14831bea08e6c0064a7cf762d34c6c24464cf9854bde9a7"
   }
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
